### ISSUE TITLE
All package versions used

### ISSUE THREAD

**Issue by pedrogzl** [rddy/deeptutor#3]
Hello, for the past few days I have been trying to run your project but still cannot figure out which package versions to use (I used versions that were released around 2017 and up to python 3.5.4 but still somehow end up with tuple comparing errors and others). Would you be able to specify which versions did you use during building?

**Comment by rddy** [comment]
gym 0.10.5 and rllab 0.1.0 should work (see https://github.com/rddy/deeptutor/issues/1 and https://github.com/rddy/deeptutor/issues/2)
