### ISSUE TITLE
reward_logs.pkl.[0-5] needed for plot not produced by notebook

### ISSUE THREAD

**Issue by melvinzhang** [rddy/deeptutor#4]
Thanks for putting up the notebook to reproduce the results of the paper!

At one point, the notebook, saves the output fo the experiment to reward_logs.pkl and in the next cell tries to read reward_logs.pkl.[0-5] which fails as only reward_logs.pkl exists.

How should reward_logs.pkl.[0-5] be generated in order to generate the plot?

**Comment by rddy** [comment]
reward_logs.pkl.[0-5] are from multiple runs of the same code that produces reward_logs.pkl
