### ISSUE TITLE
What is the dataset used?

### ISSUE THREAD

**Issue by DaehanKim** [rddy/deeptutor#5]
Thank you for the good work on RL based review recommendation!

after reading your article, I could not find the information about dataset used in your experiments. Is it assistment or ednet as in typical knowledge tracing task? I’d appreciate if you could provide it.

also I wonder what the semantic difference is between typical exercise recommendation that aims to maximizing student understanding across all knowledge concepts, and this recall-oriented recommendation.

**Comment by rddy** [comment]
We didn't analyze a benchmark dataset in our experiments. The student simulation parameter values were loosely based on prior work (see the "Implementation details" paragraph on page 5). That being said, I think there's an opportunity for follow-up work that estimates these parameter values from data (see Section 6.1).

I think that "exercise recommendation" and "recall-oriented recommendation" are essentially solving the same problem, but under different implicit assumptions about student memory. [Mozer et al. (2016)](https://home.cs.colorado.edu/~mozer/Research/Selected%20Publications/reprints/MozerLindsey2017.pdf) might be a good place to start reading about the connections between these two ideas.
